# Generated by Django 4.2 on 2023-05-12 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('des', models.TextField()),
                ('pic', models.FileField(default='sad.jpg', upload_to='blog_photos')),
                ('time', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('food', 'food'), ('lifestyle', 'lifestyle'), ('fashion', 'fashion'), ('beauty', 'beauty')], max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.user')),
            ],
        ),
    ]
